### ISSUE TITLE
/usr/bin/ld: cannot find -lBoost::timer 

### ISSUE THREAD

**Issue by lantianran** [RobustFieldAutonomyLab/DiSCo-SLAM#1]
`/usr/bin/ld: cannot find -lBoost::timer
collect2: error: ld returned 1 exit status
LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/build.make:760: recipe for target '/home/nature/LIO_SAM_ws/devel/lib/lio_sam/lio_sam_imuPreintegration' failed
make[2]: *** [/home/nature/LIO_SAM_ws/devel/lib/lio_sam/lio_sam_imuPreintegration] Error 1
CMakeFiles/Makefile2:3107: recipe for target 'LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/all' failed
make[1]: *** [LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/all] Error 2
make[1]: *** waiting for unfinished task....
/usr/bin/ld: cannot find  -lBoost::timer
collect2: error: ld returned 1 exit status
LIO-SAM/CMakeFiles/lio_sam_mapFusion.dir/build.make:720: recipe for target '/home/nature/LIO_SAM_ws/devel/lib/lio_sam/lio_sam_mapFusion' failed
make[2]: *** [/home/nature/LIO_SAM_ws/devel/lib/lio_sam/lio_sam_mapFusion] Error 1
CMakeFiles/Makefile2:3202: recipe for target 'LIO-SAM/CMakeFiles/lio_sam_mapFusion.dir/all' failed
make[1]: *** [LIO-SAM/CMakeFiles/lio_sam_mapFusion.dir/all] Error 2
/usr/bin/ld: cannot find -lBoost::timer
collect2: error: ld returned 1 exit status
LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/build.make:760: recipe for target '/home/nature/LIO_SAM_ws/devel/lib/lio_sam/lio_sam_mapOptmization' failed
make[2]: *** [/home/nature/LIO_SAM_ws/devel/lib/lio_sam/lio_sam_mapOptmization] Error 1
CMakeFiles/Makefile2:2778: recipe for target 'LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/all' failed
make[1]: *** [LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed`
I have build libnabo and boost , and add them to my library path.But it seems not work.
I have build libnabo 1.0.7 and boost 1.65.1 .
I can find the libboost_timer in /usr/lib 
![image](https://user-images.githubusercontent.com/73154000/157826368-603711f9-3fd5-4170-9469-80e003a9aeb7.png)
I'm sorry to disturb you. @yeweihuang  
I would appreciate it if you could give me some ideas

**Comment by lantianran** [comment]
I have to close this issue because I have solved it.
add this line to the CmakeLists:
find_package(Boost REQUIRED COMPONENTS timer)

**Comment by BIT-TYJ** [comment]
> I have to close this issue because I have solved it. add this line to the CmakeLists: find_package(Boost REQUIRED COMPONENTS timer)

大佬你好，我也是 BIT的，复现这个代码遇到了问题，不知道可不可以请教你一下
