### ISSUE TITLE
Data collected at different time

### ISSUE THREAD

**Issue by wolf943134497** [RobustFieldAutonomyLab/DiSCo-SLAM#13]
Hi @yeweihuang  Thanks for your great work

If I record two path data at different time, and the two path data have overlapping area.
Can Disco-SLAM merge two path map into one big map. Thanks

**Comment by yeweihuang** [comment]
Hi, if the timestamp is modified to be synchronized, and the overlap is large enough, the algorithm would probably works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: davci ***@***.***>
Sent: Wednesday, April 10, 2024 11:24:46 PM
To: RobustFieldAutonomyLab/DiSCo-SLAM ***@***.***>
Cc: Yewei Huang ***@***.***>; Mention ***@***.***>
Subject: [RobustFieldAutonomyLab/DiSCo-SLAM] Data collected at different time (Issue #13)

CAUTION: This email originated from outside the organization. Please do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @yeweihuang<https://github.com/yeweihuang> Thanks for your great work

If I record two path data at different time, and the two path data have overlapping area.
Can Disco-SLAM merge two path map into one big map. Thanks

**Comment by wolf943134497** [comment]
hi @yeweihuang  Thanks for your rapid reply.
I found there is a compare_timestamp(int id_0, int id_1) function in mapFusion.cpp. can you give me some advice about how to modify the code to merge data at different times?  I think judging whether it is an overlapping area mainly depends on loop detection，once a loop is detected，Loop constraints can be added to PGO，Why time synchronization is necessary？ thanks
